# Generated by Django 6.0.6 on 2026-06-21 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_role_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='father_status',
            field=models.CharField(choices=[('alive', 'در قید حیات'), ('dead', 'فوت شده'), ('divorced', 'متارکه'), ('other', 'سایر')], default='alive', max_length=10, verbose_name='وضعیت پدر'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'مرد'), ('F', 'زن')], max_length=1, null=True, verbose_name='جنسیت'),
        ),
        migrations.AddField(
            model_name='user',
            name='guardian_notes',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات سرپرست'),
        ),
        migrations.AddField(
            model_name='user',
            name='mother_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='نام مادر'),
        ),
        migrations.AddField(
            model_name='user',
            name='mother_status',
            field=models.CharField(choices=[('alive', 'در قید حیات'), ('dead', 'فوت شده'), ('divorced', 'متارکه'), ('other', 'سایر')], default='alive', max_length=10, verbose_name='وضعیت مادر'),
        ),
    ]
