# Generated by Django 6.0.6 on 2026-06-23 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_national_code_alter_user_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='father_status',
        ),
        migrations.RemoveField(
            model_name='user',
            name='guardian_notes',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mother_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mother_status',
        ),
    ]
