# Generated by Django 6.0.6 on 2026-06-23 07:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mother_name', models.CharField(max_length=100, verbose_name='نام مادر')),
                ('father_status', models.CharField(choices=[('alive', 'در قید حیات'), ('dead', 'فوت شده'), ('divorced', 'متارکه'), ('other', 'سایر')], default='alive', max_length=10, verbose_name='وضعیت پدر')),
                ('mother_status', models.CharField(choices=[('alive', 'در قید حیات'), ('dead', 'فوت شده'), ('divorced', 'متارکه'), ('other', 'سایر')], default='alive', max_length=10, verbose_name='وضعیت مادر')),
                ('guardian_notes', models.TextField(blank=True, null=True, verbose_name='توضیحات سرپرست')),
                ('health_condition', models.BooleanField(default=True, max_length=1, unique=True)),
                ('medical_notes', models.TextField(blank=True, null=True, verbose_name='وضعیت سلامتی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پروفایل دانش\u200cآموز',
                'verbose_name_plural': 'پروفایل دانش\u200cآموزان',
            },
        ),
    ]
