# Generated by Django 6.0.6 on 2026-06-23 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='mother_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام مادر'),
        ),
    ]
