# Generated by Django 6.0.6 on 2026-06-23 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_studentprofile_mother_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='medical_notes',
            field=models.TextField(blank=True, null=True, verbose_name='بیماری خاص'),
        ),
    ]
