# Generated by Django 6.0.6 on 2026-06-11 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام شهر')),
            ],
            options={
                'verbose_name': 'شهر',
                'verbose_name_plural': 'شهرها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EducationLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='عنوان مقطع')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='کد مقطع')),
            ],
            options={
                'verbose_name': 'مقطع تحصیلی',
                'verbose_name_plural': 'مقاطع تحصیلی',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='SchoolType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='نوع مدرسه')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='کد نوع مدرسه')),
            ],
            options={
                'verbose_name': 'نوع مدرسه',
                'verbose_name_plural': 'انواع مدرسه',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام منطقه')),
                ('code', models.CharField(blank=True, max_length=20, null=True, verbose_name='کد منطقه')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='core.city', verbose_name='شهر')),
            ],
            options={
                'verbose_name': 'منطقه',
                'verbose_name_plural': 'مناطق',
                'ordering': ['city__name', 'name'],
                'unique_together': {('city', 'name')},
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام مدرسه')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='کد مدرسه')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schools', to='core.city', verbose_name='شهر')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schools', to='core.district', verbose_name='منطقه')),
                ('education_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schools', to='core.educationlevel', verbose_name='مقطع تحصیلی')),
                ('school_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schools', to='core.schooltype', verbose_name='نوع مدرسه')),
            ],
            options={
                'verbose_name': 'مدرسه',
                'verbose_name_plural': 'مدارس',
                'ordering': ['name'],
            },
        ),
    ]
