# Generated by Django 6.0.6 on 2026-06-11 10:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, unique=True, verbose_name='عنوان سال تحصیلی')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(verbose_name='تاریخ پایان')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'سال تحصیلی',
                'verbose_name_plural': 'سال\u200cهای تحصیلی',
                'ordering': ['-start_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='educationlevel',
            options={'ordering': ['name'], 'verbose_name': 'مقطع تحصیلی', 'verbose_name_plural': 'مقاطع تحصیلی'},
        ),
        migrations.AlterModelOptions(
            name='schooltype',
            options={'ordering': ['name'], 'verbose_name': 'نوع مدرسه', 'verbose_name_plural': 'انواع مدرسه'},
        ),
        migrations.RenameField(
            model_name='schooltype',
            old_name='title',
            new_name='name',
        ),
        migrations.AlterUniqueTogether(
            name='district',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='educationlevel',
            name='code',
        ),
        migrations.RemoveField(
            model_name='educationlevel',
            name='title',
        ),
        migrations.RemoveField(
            model_name='school',
            name='city',
        ),
        migrations.RemoveField(
            model_name='school',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='schooltype',
            name='code',
        ),
        migrations.AddField(
            model_name='city',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AddField(
            model_name='district',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AddField(
            model_name='educationlevel',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AddField(
            model_name='educationlevel',
            name='name',
            field=models.CharField(default=datetime.date.today, max_length=100, unique=True, verbose_name='مقطع تحصیلی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='شماره تماس'),
        ),
        migrations.AddField(
            model_name='schooltype',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AddConstraint(
            model_name='district',
            constraint=models.UniqueConstraint(fields=('city', 'name'), name='uniq_district_per_city'),
        ),
        migrations.RemoveField(
            model_name='district',
            name='code',
        ),
    ]
