# Generated by Django 6.0.6 on 2026-06-14 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_academicyear_alter_educationlevel_options_and_more'),
        ('users', '0002_alter_role_options_alter_user_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AchievementCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی افتخار',
                'verbose_name_plural': 'دسته\u200cبندی افتخارات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AchievementLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'سطح افتخار',
                'verbose_name_plural': 'سطوح افتخار',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AchievementRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'رتبه افتخار',
                'verbose_name_plural': 'رتبه\u200cهای افتخار',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'نوع تشکل',
                'verbose_name_plural': 'انواع تشکل',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی مهارت',
                'verbose_name_plural': 'دسته\u200cبندی مهارت\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AchievementType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='types', to='cultural.achievementcategory')),
            ],
            options={
                'verbose_name': 'نوع افتخار',
                'verbose_name_plural': 'انواع افتخار',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organizations', to='core.academicyear')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to='core.school')),
                ('organization_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organizations', to='cultural.organizationtype')),
            ],
            options={
                'verbose_name': 'تشکل',
                'verbose_name_plural': 'تشکل\u200cها',
                'ordering': ['school', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('organization_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='cultural.organizationtype')),
            ],
            options={
                'verbose_name': 'سمت تشکل',
                'verbose_name_plural': 'سمت\u200cهای تشکل',
                'ordering': ['organization_type', 'title'],
                'unique_together': {('organization_type', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='skills', to='cultural.skillcategory')),
            ],
            options={
                'verbose_name': 'مهارت',
                'verbose_name_plural': 'مهارت\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('event_date', models.DateField()),
                ('is_pre_school', models.BooleanField(default=False)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_achievements', to='core.academicyear')),
                ('achievement_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_achievements', to='cultural.achievementtype')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_achievements', to='cultural.achievementlevel')),
                ('rank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_achievements', to='cultural.achievementrank')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_achievements', to='core.school')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'افتخار کاربر',
                'verbose_name_plural': 'افتخارات کاربران',
                'ordering': ['-event_date', 'user'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='cultural.organization')),
                ('user_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_memberships', to='users.userrole')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='cultural.organizationposition')),
            ],
            options={
                'verbose_name': 'عضویت در تشکل',
                'verbose_name_plural': 'عضویت\u200cها در تشکل',
                'ordering': ['organization', 'user_role'],
                'unique_together': {('user_role', 'organization', 'position')},
            },
        ),
        migrations.CreateModel(
            name='UserSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(blank=True, max_length=30, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_pre_school', models.BooleanField(default=False)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_skills', to='core.academicyear')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_skills', to='cultural.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'مهارت کاربر',
                'verbose_name_plural': 'مهارت\u200cهای کاربران',
                'ordering': ['user', 'skill'],
                'unique_together': {('user', 'skill', 'academic_year', 'is_pre_school')},
            },
        ),
    ]
